version: "3.8"

services:
  frontend:
    container_name: mineops-front
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
      
  backend:
    container_name: mineops-back
    build: ./backend
    ports: 
      - "8000:8000"
    restart: always