name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4

      # Optionnel : installer docker-compose si besoin
      # - name: Install docker compose
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker-compose

      # - name: Build and start docker compose
      #   run: docker compose up -d --build

      # - name: Run tests
      #   run: echo "No tests yet"

      # - name: Stop docker compose
      #   run: docker compose down

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build backend image
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            docker build -t ghcr.io/sown21/mineops/backend:$VERSION -t ghcr.io/sown21/mineops/backend:latest ./backend
          else
            docker build -t ghcr.io/sown21/mineops/backend:${GITHUB_SHA} ./backend
          fi

      - name: Build frontend image
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            docker build -t ghcr.io/sown21/mineops/frontend:$VERSION -t ghcr.io/sown21/mineops/frontend:latest ./frontend
          else
            docker build -t ghcr.io/sown21/mineops/frontend:${GITHUB_SHA} ./frontend
          fi

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push backend image
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            docker push ghcr.io/sown21/mineops/backend:$VERSION
            docker push ghcr.io/sown21/mineops/backend:latest
          else
            docker push ghcr.io/sown21/mineops/backend:${GITHUB_SHA}
          fi

      - name: Push frontend image
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            docker push ghcr.io/sown21/mineops/frontend:$VERSION
            docker push ghcr.io/sown21/mineops/frontend:latest
          else
            docker push ghcr.io/sown21/mineops/frontend:${GITHUB_SHA}
          fi