name: CI 

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout-code
        uses: actions/checkout@v4

      # - name: Install docker compose
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker-compose

      # - name: Build and start docker compose
      #   run: docker compose up -d --build_push

      # - name: Run tests
      #   run: echo "No tests yet"

      # - name: Stop docker compose
      #   run: docker compose down

      - name: Build backend image
        run: docker build -t ghcr.io/sown21/mineops/backend:${{ github.sha }} ./backend

      - name: Build frontend image
        run: docker build -t ghcr.io/sown21/mineops/frontend:${{ github.sha }} ./frontend

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push backend image
        run: docker push ghcr.io/sown21/mineops/backend:${{ github.sha }}

      - name: Push frontend image
        run: docker push ghcr.io/sown21/mineops/frontend:${{ github.sha }}