name: Cleanup old GHCR images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  ghcr-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: List and delete old backend images (keep 3)
        env:
          PACKAGE_NAME: mineops%2Fbackend 
          KEEP: 10
        run: |
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Package name: mineops/backend"
          
          # Tester d'abord si le package existe
          if ! gh api "/orgs/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME" >/dev/null 2>&1; then
            echo "Package not found in organization. Trying user packages..."
            if ! gh api "/users/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME" >/dev/null 2>&1; then
              echo "Package not found. Skipping cleanup."
              exit 0
            else
              ENDPOINT_PREFIX="/users/${{ github.repository_owner }}"
            fi
          else
            ENDPOINT_PREFIX="/orgs/${{ github.repository_owner }}"
          fi
          
          echo "Using endpoint: $ENDPOINT_PREFIX"
          
          # Récupérer les versions
          versions=$(gh api "$ENDPOINT_PREFIX/packages/container/$PACKAGE_NAME/versions?per_page=100" \
            --jq 'sort_by(.created_at) | reverse')
          
          if [ -z "$versions" ] || [ "$versions" = "null" ]; then
            echo "No versions found"
            exit 0
          fi
          
          # Compter le nombre total de versions
          total=$(echo "$versions" | jq 'length')
          echo "Total backend versions found: $total"
          
          if [ "$total" -gt "$KEEP" ]; then
            # Calculer combien supprimer
            to_delete=$((total - KEEP))
            echo "Deleting $to_delete old backend versions (keeping $KEEP newest)"
            
            # Récupérer les IDs des versions à supprimer (les plus anciennes)
            ids=$(echo "$versions" | jq -r ".[-$to_delete:][].id")
            
            for id in $ids; do
              if [ -n "$id" ] && [ "$id" != "null" ]; then
                echo "Deleting backend version ID: $id"
                gh api --method DELETE "$ENDPOINT_PREFIX/packages/container/$PACKAGE_NAME/versions/$id" || echo "Failed to delete $id"
                sleep 1
              fi
            done
          else
            echo "Not enough backend versions to clean up (found $total, keeping $KEEP)"
          fi

      - name: List and delete old frontend images (keep 3)
        env:
          PACKAGE_NAME: mineops%2Ffrontend
          KEEP: 10
        run: |
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Package name: mineops/frontend"
          
          # Tester d'abord si le package existe
          if ! gh api "/orgs/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME" >/dev/null 2>&1; then
            echo "Package not found in organization. Trying user packages..."
            if ! gh api "/users/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME" >/dev/null 2>&1; then
              echo "Package not found. Skipping cleanup."
              exit 0
            else
              ENDPOINT_PREFIX="/users/${{ github.repository_owner }}"
            fi
          else
            ENDPOINT_PREFIX="/orgs/${{ github.repository_owner }}"
          fi
          
          echo "Using endpoint: $ENDPOINT_PREFIX"
          
          # Récupérer les versions
          versions=$(gh api "$ENDPOINT_PREFIX/packages/container/$PACKAGE_NAME/versions?per_page=100" \
            --jq 'sort_by(.created_at) | reverse')
          
          if [ -z "$versions" ] || [ "$versions" = "null" ]; then
            echo "No versions found"
            exit 0
          fi
          
          # Compter le nombre total de versions
          total=$(echo "$versions" | jq 'length')
          echo "Total frontend versions found: $total"
          
          if [ "$total" -gt "$KEEP" ]; then
            # Calculer combien supprimer
            to_delete=$((total - KEEP))
            echo "Deleting $to_delete old frontend versions (keeping $KEEP newest)"
            
            # Récupérer les IDs des versions à supprimer (les plus anciennes)
            ids=$(echo "$versions" | jq -r ".[-$to_delete:][].id")
            
            for id in $ids; do
              if [ -n "$id" ] && [ "$id" != "null" ]; then
                echo "Deleting frontend version ID: $id"
                gh api --method DELETE "$ENDPOINT_PREFIX/packages/container/$PACKAGE_NAME/versions/$id" || echo "Failed to delete $id"
                sleep 1
              fi
            done
          else
            echo "Not enough frontend versions to clean up (found $total, keeping $KEEP)"
          fi

      - name: List and delete old nginx images (keep 3)
        env:
          PACKAGE_NAME: mineops%2Fnginx
          KEEP: 10
        run: |
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Package name: mineops/nginx"
          
          # Tester d'abord si le package existe
          if ! gh api "/orgs/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME" >/dev/null 2>&1; then
            echo "Package not found in organization. Trying user packages..."
            if ! gh api "/users/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME" >/dev/null 2>&1; then
              echo "Package not found. Skipping cleanup."
              exit 0
            else
              ENDPOINT_PREFIX="/users/${{ github.repository_owner }}"
            fi
          else
            ENDPOINT_PREFIX="/orgs/${{ github.repository_owner }}"
          fi
          
          echo "Using endpoint: $ENDPOINT_PREFIX"
          
          # Récupérer les versions
          versions=$(gh api "$ENDPOINT_PREFIX/packages/container/$PACKAGE_NAME/versions?per_page=100" \
            --jq 'sort_by(.created_at) | reverse')
          
          if [ -z "$versions" ] || [ "$versions" = "null" ]; then
            echo "No versions found"
            exit 0
          fi
          
          # Compter le nombre total de versions
          total=$(echo "$versions" | jq 'length')
          echo "Total nginx versions found: $total"
          
          if [ "$total" -gt "$KEEP" ]; then
            # Calculer combien supprimer
            to_delete=$((total - KEEP))
            echo "Deleting $to_delete old nginx versions (keeping $KEEP newest)"
            
            # Récupérer les IDs des versions à supprimer (les plus anciennes)
            ids=$(echo "$versions" | jq -r ".[-$to_delete:][].id")
            
            for id in $ids; do
              if [ -n "$id" ] && [ "$id" != "null" ]; then
                echo "Deleting nginx version ID: $id"
                gh api --method DELETE "$ENDPOINT_PREFIX/packages/container/$PACKAGE_NAME/versions/$id" || echo "Failed to delete $id"
                sleep 1
              fi
            done
          else
            echo "Not enough nginx versions to clean up (found $total, keeping $KEEP)"
          fi